=== maciekozak/XML-course/Project task 2/storeDefinition.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema
		xmlns:xs="http://www.w3.org/2001/XMLSchema"
		targetNamespace="http://example.com/store"
		xmlns:ms="http://example.com/store"
		elementFormDefault="unqualified"
		attributeFormDefault="unqualified"
>
	<xs:group name="personGroup">
		<xs:sequence>
			<xs:element name="name" type="ms:personType"/>
			<xs:element name="surname" type="ms:personType"/>
		</xs:sequence>
	</xs:group>

	<xs:simpleType name="personType">
		<xs:restriction base="xs:string">
			<xs:minLength value="2"/>
			<xs:maxLength value="25"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="authorType">
		<xs:choice>
			<xs:sequence>
				<xs:group ref="ms:personGroup"/>
				<xs:element name="IDno" type="xs:integer"/>
				<xs:element name="date_of_last_modification" type="xs:date"/>
				<xs:element name="faculty" type="ms:facultyType"/>
			</xs:sequence>
			<xs:sequence>
				<xs:element name="IDno" type="xs:integer"/>
				<xs:element name="date_of_last_modification" type="xs:date"/>
				<xs:element name="faculty" type="ms:facultyType"/>
			</xs:sequence>
		</xs:choice>
	</xs:complexType>

	<xs:attributeGroup name="facultyGroup">
		<xs:attribute name="course" type="ms:stringType" use="required"/>
		<xs:attribute name="university" type="ms:stringType"/> <!-- maxlength -->
	</xs:attributeGroup>

	<xs:simpleType name="stringType">
		<xs:restriction base="xs:string">
			<xs:minLength value="2"/>
			<xs:maxLength value="100"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="facultyType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attributeGroup ref="ms:facultyGroup"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<!-- -->
	<xs:complexType name="makeType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="id" type="xs:string" use="required"/>
				<xs:attribute name="origin" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="makesType">
		<xs:sequence>
			<xs:element name="make" type="ms:makeType" minOccurs="0" maxOccurs="10">
				<xs:key name="makeReference">
					<xs:selector xpath="makes/make"/>
					<xs:field xpath="@id"/>
				</xs:key>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="makeInListType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="idref" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:simpleType name="fullNameType">
		<xs:restriction base="xs:string">
			<xs:minLength value="2"/>
			<xs:maxLength value="150"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="eanType" final="#all">
		<xs:restriction base="xs:string">
			<xs:pattern value="PL\d{6}"/>
			<xs:pattern value="DE\d{6}"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="batteryType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="unit" type="xs:string" use="required" fixed="mAh"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="resolutionType">
		<xs:simpleContent>
			<xs:extension base="xs:double">
				<xs:attribute name="unit" type="xs:string" use="required" fixed="inch"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="screenType">
		<xs:all>
			<xs:element name="surface" type="xs:string"/>
			<xs:element name="resolution" type="ms:resolutionType"/>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="specificationType">
		<xs:all>
			<xs:element name="CPU" type="xs:string"/>
			<xs:element name="RAM" type="xs:string"/>
			<xs:element name="graphics" type="xs:string"/>
			<xs:element name="battery" type="ms:batteryType"/>
			<xs:element name="screen" type="ms:screenType"/>
		</xs:all>
	</xs:complexType>

	<xs:simpleType name="currencyType" >
		<xs:restriction base="xs:string">
			<xs:enumeration value="PLN"/>
			<xs:enumeration value="USD"/>
			<xs:enumeration value="EUR"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="priceRestricted">
		<xs:restriction base="xs:double">
			<xs:minInclusive value="1.0"/>
			<xs:maxExclusive value="10000.00"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="priceType">
		<xs:simpleContent>
			<xs:extension base="ms:priceRestricted">
				<xs:attribute name="currency" type="ms:currencyType" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="laptopType">
		<xs:all>
			<xs:element name="makeInList" type="ms:makeInListType">
				<xs:keyref name="makeRef" refer="ms:makeReference">
					<xs:selector xpath="laptops/laptop/makeInList"/>
					<xs:field xpath="@idref"/>
				</xs:keyref>
			</xs:element>
			<xs:element name="fullName" type="ms:fullNameType"/>
			<xs:element name="ean" type="ms:eanType"/>
			<xs:element name="specification" type="ms:specificationType"/>
			<xs:element name="premiere" type="xs:date"/>
			<xs:element name="price" type="ms:priceType"/>
		</xs:all>
		<xs:attribute name="no" type="xs:integer" use="required"/>
	</xs:complexType>

	<xs:complexType name="laptopsType">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="laptop" type="ms:laptopType"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="storeType">
		<xs:all>
			<xs:element name="author" type="ms:authorType"/>
			<xs:element name="makes" type="ms:makesType"/>
			<xs:element name="laptops" type="ms:laptopsType">

			</xs:element>
		</xs:all>
	</xs:complexType>

	<xs:element name="store" type="ms:storeType"/>

</xs:schema>

=== maciekozak/XML-course/Project task 2/store.xml
<?xml version="1.0" encoding="UTF-8"?>

<store:store
	xmlns:store="http://example.com/store"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://example.com/store storeDefinition.xsd"
>
    <author>
		<name>Maciej</name>
		<surname>Kopa</surname>
		<IDno>230451</IDno>
		<date_of_last_modification>2000-11-22</date_of_last_modification>
		<faculty course="Information Technology" university="TUL">IFE</faculty>
    </author>
    
    <makes>
		<make id='m1' origin='China'>ASUS</make>
		<make id='m2' origin='China'>Acer</make>
		<make id='m3' origin='China'>Huawei</make>
		<make id='m4' origin='South Korea'>LG</make>
		<make id='m5' origin='USA'>Apple</make>
		<make id='m6' origin='USA'>HP</make>
		<make id='m7' origin='China'>Lenovo</make>
		<make id='m8' origin='USA'>Dell</make>
		<make id='m9' origin='China'>MSI</make>
    </makes>
	
    <laptops>
		<laptop no="1">
			<makeInList idref='m1'/>
			<fullName>ASUS TUF Gaming FX505GT</fullName>
			<ean>PL588288</ean>
			<specification>
				<CPU>Intel Core i5-9300H</CPU>
				<RAM>16GB</RAM>
				<graphics>NVIDIA GeForce GTX 1650</graphics>
				<battery unit='mAh'>4212</battery>
				<screen>
					<surface>Mat</surface>
					<resolution unit='inch'>15.6</resolution>
				</screen>
			</specification>
			<premiere>2020-06-05</premiere>
			<price currency='PLN'>4099.00</price>
		</laptop>

		<laptop no="2">
			<makeInList idref='m5'/>
			<fullName>Apple MacBook Air</fullName>
			<ean>DE588471</ean>
			<specification>
				<CPU>AMD Ryzen™ 3 3250U</CPU>
				<RAM>8GB</RAM>
				<graphics>AMD Radeon Graphics</graphics>
				<battery unit='mAh'>3500</battery>
				<screen>
					<surface>Mat</surface>
					<resolution unit='inch'>14.0</resolution>
				</screen>
			</specification>
			<premiere>2000-02-04</premiere>
			<price currency='USD'>1199.00</price>
		</laptop>

		<laptop no='3'>
			<makeInList idref='m3'/>
			<fullName>Huawei MateBook D 15</fullName>
			<ean>DE541793</ean>
			<specification>
				<CPU>AMD Ryzen™ 5 3500U</CPU>
				<RAM>8GB</RAM>
				<graphics>AMD Radeon™ Vega 8</graphics>
				<battery unit='mAh'>3665</battery>
				<screen>
					<surface>Mat</surface>
					<resolution unit='inch'>15.6</resolution>
				</screen>
			</specification>
			<premiere>2020-03-20</premiere>
			<price currency='PLN'>3049.00</price>
		</laptop>
		
		<laptop no='4'>
			<makeInList idref='m2'/>
			<fullName>Acer Aspire 5</fullName>
			<ean>PL575758</ean>
			<specification>
				<CPU>Intel Core i5-1035G1</CPU>
				<RAM>12GB</RAM>
				<graphics>NVIDIA GeForce MX350</graphics>
				<battery unit='mAh'>4471</battery>
				<screen>
					<surface>Mat</surface>
					<resolution unit='inch'>15.6</resolution>
				</screen>
			</specification>
			<premiere>2020-08-10</premiere>
			<price currency='PLN'>3549.00</price>
		</laptop>
		<!-- EDIT THE REST
		<laptop no='5'>
			<makeInList idref='m2'/>
			<fullName>Acer Swift 3</fullName>
			<ID>563179</ID>
			<specification>
				<CPU>AMD Ryzen™ 5 4500U</CPU>
				<RAM type='GB'>16</RAM>
				<GraphicsCard>AMD Radeon™ Graphic</GraphicsCard>
				<battery type='mAh'>3203</battery>
				<screen>
					<type>Mat</type>
					<size type='inch'>14,0</size>
				</screen>
			</specification>
			<premiere>20/09/2020</premiere>
			<price type='PLN'>3599,0</price>	
		</laptop>
		
		<laptop no='6'>
			<makeInList idref='m3'/>
			<fullName>Huawei MateBook D 14</fullName>
			<ID>557204</ID>
			<specification>
				<CPU>AMD Ryzen™ 5 3500U</CPU>
				<RAM type='GB'>8</RAM>
				<GraphicsCard>AMD Radeon™ Vega 8</GraphicsCard>
				<battery type='mAh'>3665</battery>
				<screen>
					<type>Mat</type>
					<size type='inch'>14,0</size>
				</screen>
			</specification>
			<premiere>17/02/2020</premiere>
			<price type='PLN'>2699,00</price>	
		</laptop>
		
		<laptop no='7'>
			<makeInList idref='m3'/>
			<fullName>Huawei MateBook D 15</fullName>
			<ID>541793</ID>
			<specification>
				<CPU>AMD Ryzen™ 5 3500U</CPU>
				<RAM type='GB'>8</RAM>
				<GraphicsCard>AMD Radeon™ Vega 8</GraphicsCard>
				<battery type='mAh'>3665</battery>
				<screen>
					<type>Mat</type>
					<size type='inch'>15,6</size>
				</screen>
			</specification>
			<premiere>20/03/2020</premiere>
			<price type='PLN'>3049,00</price>	
		</laptop>
		
		<laptop no='8'>
			<makeInList idref='m4'/>
			<fullName>LG GRAM 17Z90N</fullName>
			<ID>568939</ID>
			<specification>
				<CPU>Intel Core i7-1065G7</CPU>
				<RAM type='GB'>8</RAM>
				<GraphicsCard>Intel Iris Plus Graphics</GraphicsCard>
				<battery type='mAh'>5040</battery>
				<screen>
					<type>Glare</type>
					<size type='inch'>17</size>
				</screen>
			</specification>
			<premiere>29/01/2020</premiere>
			<price type='PLN'>7299,00</price>	
		</laptop>
		
		<laptop no='9'>
			<makeInList idref='m2'/>
			<fullName>Acer Nitro 5</fullName>
			<ID>571702</ID>
			<specification>
				<CPU>Intel® Core™ i5-10300H</CPU>
				<RAM type='GB'>16</RAM>
				<GraphicsCard>NVIDIA GeForce GTX 1650Ti</GraphicsCard>
				<battery type='mAh'>3405</battery>
				<screen>
					<type>Mat</type>
					<size type='inch'>15,6</size>
				</screen>
			</specification>
			<premiere></premiere>
			<price type='PLN'>4049,00</price>	
		</laptop>
		
		<laptop no='10'>
			<makeInList idref='m5'/>
			<fullName>Apple MacBook Air</fullName>
			<ID>553995</ID>
			<specification>
				<CPU>Intel Core i5-1030NG7</CPU>
				<RAM type='GB'>8</RAM>
				<GraphicsCard>Intel Iris Plus Graphics</GraphicsCard>
				<battery type='mAh'>2890</battery>
				<screen>
					<type>Glare</type>
					<size type='inch'>13,3</size>
				</screen>
			</specification>
			<premiere>03/03/2019</premiere>
			<price type='PLN'>5399,00</price>	
		</laptop>
		
		<laptop no='11'>
			<makeInList idref='m6'/>
			<fullName>HP 15s</fullName>
			<ID>582145</ID>
			<specification>
				<CPU>AMD Ryzen™ 5 3500U</CPU>
				<RAM type='GB'>16</RAM>
				<GraphicsCard>AMD Radeon™ Vega 8</GraphicsCard>
				<battery type='mAh'>3900</battery>
				<screen>
					<type>Mat</type>
					<size type='inch'>15,6</size>
				</screen>
			</specification>
			<premiere>28/09/2020</premiere>
			<price type='PLN'>2999,00</price>	
		</laptop>
		
		<laptop no='12'>
			<makeInList idref='m6'/>
			<fullName>HP 14s</fullName>
			<ID>583992</ID>
			<specification>
				<CPU>Intel Core i3-1005G1</CPU>
				<RAM type='GB'>8</RAM>
				<GraphicsCard>Intel UHD Graphics</GraphicsCard>
				<battery type='mAh'></battery>
				<screen>
					<type>Mat</type>
					<size type='inch'>14,0</size>
				</screen>
			</specification>
			<premiere>21/07/2020</premiere>
			<price type='PLN'>2449,00</price>	
		</laptop>
		
		<laptop no='13'>
			<makeInList idref='m7'/>
			<fullName>Lenovo IdeaPad L340-17</fullName>
			<ID>570331</ID>
			<specification>
				<CPU>Intel Core i5-9300HF</CPU>
				<RAM type='GB'>16</RAM>
				<GraphicsCard>NVIDIA GeForce GTX 1650</GraphicsCard>
				<battery type='mAh'>4000</battery>
				<screen>
					<type>Mat</type>
					<size type='inch'>17,3</size>
				</screen>
			</specification>
			<premiere>20/01/2020</premiere>
			<price type='PLN'>3699,00</price>	
		</laptop>
		
		<laptop no='14'>
			<makeInList idref='m8'/>
			<fullName>Dell Inspiron 5505</fullName>
			<ID>572924</ID>
			<specification>
				<CPU>AMD Ryzen™ 5 4500U</CPU>
				<RAM type='GB'>16</RAM>
				<GraphicsCard>AMD Radeon™ Graphics</GraphicsCard>
				<battery type='mAh'>3378</battery>
				<screen>
					<type>Mat</type>
					<size type='inch'>15,6</size>
				</screen>
			</specification>
			<premiere>23/04/2020</premiere>
			<price type='PLN'>3899,00</price>	
		</laptop>
		
		<laptop no='15'>
			<makeInList idref='m1'/>
			<fullName>ASUS D413DA-EK260T</fullName>
			<ID>588471</ID>
			<specification>
				<CPU>AMD Ryzen™ 3 3250U</CPU>
				<RAM type='GB'>8</RAM>
				<GraphicsCard>AMD Radeon™ Graphics</GraphicsCard>
				<battery type='mAh'>3299</battery>
				<screen>
					<type>Mat</type>
					<size type='inch'>14,0</size>
				</screen>
			</specification>
			<premiere>01/03/2020</premiere>
			<price type='PLN'>2199,00</price>	
		</laptop>
		
		<laptop no='16'>
			<makeInList idref='m7'/>
			<fullName>Lenovo IdeaPad 3-15</fullName>
			<ID>576974</ID>
			<specification>
				<CPU>Intel Core i5-1035G1</CPU>
				<RAM type='GB'>20</RAM>
				<GraphicsCard>Intel UHD Graphics</GraphicsCard>
				<battery type='mAh'>4610</battery>
				<screen>
					<type>Mat</type>
					<size type='inch'>15,6</size>
				</screen>
			</specification>
			<premiere>06/07/2020</premiere>
			<price type='PLN'>3249,00</price>	
		</laptop>
		
		<laptop no='17'>
			<makeInList idref='m3'/>
			<fullName>Huawei MateBook 13</fullName>
			<ID>574554</ID>
			<specification>
				<CPU>AMD Ryzen™ 5 3500U</CPU>
				<RAM type='GB'>8</RAM>
				<GraphicsCard>AMD Radeon™ Vega 8</GraphicsCard>
				<battery type='mAh'>3660</battery>
				<screen>
					<type>Glare</type>
					<size type='inch'>13,0</size>
				</screen>
			</specification>
			<premiere>09/09/2020</premiere>
			<price type='PLN'>2979,00</price>	
		</laptop>
		
		<laptop no='18'>
			<makeInList idref='m2'/>
			<fullName>Acer Swift 3</fullName>
			<ID>581247</ID>
			<specification>
				<CPU>AMD Ryzen™ 3 4300U</CPU>
				<RAM type='GB'>8</RAM>
				<GraphicsCard>AMD Radeon™ Graphics</GraphicsCard>
				<battery type='mAh'>3660</battery>
				<screen>
					<type>Mat</type>
					<size type='inch'>14,0</size>
				</screen>
			</specification>
			<premiere>07/08/2020</premiere>
			<price type='PLN'>2699,00</price>	
		</laptop>
		
		<laptop no='19'>
			<makeInList idref='m8'/>
			<fullName>Dell Vostro 3490</fullName>
			<ID>520646</ID>
			<specification>
				<CPU>Intel Core i5-10210U</CPU>
				<RAM type='GB'>8</RAM>
